#
# VanishNoPacket
#   A fine choice of invisibility for the discerning server administrator.
#   https://www.kitteh.org
#
#  See documentation for details:
#  https://dev.bukkit.org/projects/vanish/pages/configuration
#
fakeannounce:
    automaticforsilentjoin: false
    join: '<yellow><player:name> joined the game.'
    quit: '<yellow><player:name> left the game.'
hooks:
    essentials: false
    dynmap: false
    discordsrv: false
    squaremap: false
permissionsupdates:
    checkonworldchange: false
effects:
    lightning:
        count: 30
double-sneak-during-vanish-switches-gamemode:
    enabled: false
    max-ms-time-between-sneaks: 750
    messagespec: '<aqua>Game mode changed to spectator!'
    messageback: '<aqua>Game mode restored!'

permtest: false
debug: false
configVersionDoNotTouch:
    SeriouslyThisWillEraseYourConfig: 10
